Stage2
kkazlov/grok pull request #2
Opened 2021-11-12 11:06 UTC by kkazlov

Stage2: Album screen, Form screen

2021-11-15 07:02 UTC, ekosiy requested changes

2021-11-15 07:02 UTC, ekosiy commented on sources/views/form/index.js
> +		this.dp.on();
это для меня не совсем очевидно. Зачем мы делаем загрузку альбомов и  on в деструкторе?

2021-11-15 07:02 UTC, ekosiy commented on sources/views/form/index.js
> +		this.dp = webix.dp(albumsDB);
какой функционал ты хочешь реализовать тут через дата процессор?

2021-11-15 07:48 UTC, kkazlov commented on sources/views/form/index.js
> +		this.dp = webix.dp(albumsDB);
При редактировании таблицы с альбомами, данные сразу посылаются на сервер. Чтобы отправлять данные только по кнопке save, я отключил dp. Когда кнопка нажимается, включаю dp.

2021-11-15 07:54 UTC, kkazlov commented on sources/views/form/index.js
> +		this.dp.on();
Это нужно для того, чтобы при переходе на другую вкладку (в частности - Albums), обновлялась коллекция и включился dp.

2021-11-16 21:16 UTC, olimed commented on sources/views/albums/table.js
> +	deleteIcon(e, id) {
аргумент `e` в данной функции не используется, можно не передавать его

2021-11-16 21:16 UTC, olimed commented on sources/views/form/album-table.js
> +			view: "datatable",
очень похож конфиг таблицы из файла sources/views/albums/table.js. Можно сделать один компонент и просто расширить в каждом из файлов

2021-11-16 21:16 UTC, olimed commented on sources/views/albums/table.js
> +			const check = (value !== "" && value.length <= 30);
я бы еще добавила проверку на строку с пробелами

2021-11-16 21:16 UTC, olimed commented on sources/views/form/album-table.js
> +	deleteIcon(e, id) {
`e` не используется в данной функции

2021-11-16 21:16 UTC, olimed commented on sources/views/form/album-table.js
> +			{updatedAlbums, deletedAlbums},
зачем этот  аргумент? этот евент вызывается только на init этого вью, когда эти Set пустые

2021-11-16 21:16 UTC, olimed commented on sources/views/form/files-table.js
> +		if (groupId) {
добавь проверку на корректность id, иначе если изменить в урле на не существующую айди и потом пытаться сохранить изменения, то будет ошибка

2021-11-17 05:08 UTC, kkazlov commented on sources/views/form/files-table.js
> +		if (groupId) {
done

2021-11-17 05:26 UTC, kkazlov commented on sources/views/form/album-table.js
> +			{updatedAlbums, deletedAlbums},
Вообще этот ивент нужен для передачи  измененных и удаленных записей в Index. Первый агрумент и хранит в себе эти данные. Но действительно, что-то нелогично было его размещать в init. Странно, что это работало)) 
Переместил его в обработчик onStoreUpdated.

2021-11-17 05:42 UTC, kkazlov commented on sources/views/form/album-table.js
> +	deleteIcon(e, id) {
done

2021-11-17 06:23 UTC, kkazlov commented on sources/views/albums/table.js
> +			const check = (value !== "" && value.length <= 30);
done

2021-11-17 08:14 UTC, kkazlov commented on sources/views/albums/table.js
> +	deleteIcon(e, id) {
done

2021-11-17 08:14 UTC, kkazlov commented on sources/views/form/album-table.js
> +			view: "datatable",
done

2021-11-18 20:50 UTC, olimed commented on sources/views/albums/table.js
> +		];
если нужно менять конфиг колонок (добавлять или удалять), то можно передать флаг для этой колонки, а в родительском классе для этой колонки использовать этот флаг в свойстве `hidden`

2021-11-18 20:50 UTC, olimed commented on sources/views/albums/table.js
> +		const checkTable = view.data.order.length;
так как таблица не имеет сортировок, то можно использовать `view.serialize()`

2021-11-18 20:50 UTC, olimed commented on sources/views/form/album-table.js
> +			{updatedAlbums, deletedAlbums},
вроде все осталось на месте...этот ивент все еще в init

2021-11-18 20:50 UTC, olimed commented on sources/views/form/album-table.js
> +		const table = this.$$("table");
лучше вызови событие и обработай его во вью с таблицей

2021-11-18 20:50 UTC, olimed commented on sources/views/form/index.js
> +			webix.ajax().del(`${albumsURL}/${id}`);
1) ajax запросы лучше помещать в try...catch
2) стоит обернуть либо в промис, либо использовать async/await, чтобы убедиться, что все удалилось

2021-11-18 20:50 UTC, olimed commented on sources/views/form/index.js
> +			webix.ajax().headers({
смотри коммент выше + это для всех ajax запросов

2021-11-18 20:50 UTC, olimed commented on sources/views/form/index.js
> +	restoreData() {
для этого лучше создать store и хранить в нем начальное значение (state) и если пользователь что-то менял, то не нужно будет это запоминать, если он нажмет Cancel,  то ты просто установишь этот state во все элементы, если нажмешь Save - обновишь state

2021-11-19 07:02 UTC, kkazlov commented on sources/views/albums/table.js
> +		];
done

2021-11-19 08:23 UTC, kkazlov commented on sources/views/albums/table.js
> +		const checkTable = view.data.order.length;
done

2021-11-19 08:57 UTC, kkazlov commented on sources/views/form/album-table.js
> +		const table = this.$$("table");
done

2021-11-22 08:22 UTC, kkazlov commented on sources/views/form/album-table.js
> +			{updatedAlbums, deletedAlbums},
done

2021-11-22 08:23 UTC, kkazlov commented on sources/views/form/index.js
> +			webix.ajax().headers({
done

2021-11-22 08:23 UTC, kkazlov commented on sources/views/form/index.js
> +			webix.ajax().del(`${albumsURL}/${id}`);
done

2021-11-22 21:34 UTC, olimed reviewed
1) когда заходишь на страницу Albums у тебя на сервер отправляется 2 запроса одинаковых 
2) когда заходишь на страницу Form идет запрос на все файлы и когда выбираешь группу, опять отправляется запрос на получение всех файлов + ты каждый раз запрашиваешь все файлы и только на клиенте их фильтруешь, почему ты это не делаешь на сервере?
3) почему удалил промисы?

2021-11-27 09:49 UTC, olimed reviewed
если используешь `async/await`, лучше также использовать `try/catch`, так как иногда бывают ошибки

2021-11-27 09:49 UTC, olimed commented on sources/views/form/files-table.js
> +				.then((files) => {
C async/await, `.then` можно использовать, но так как await автоматически ожидает завершения выполнения промиса, то можно просто получить результат и дальше выполнять нужные действия, а ошибки если будут, словит `catch`

2021-11-27 09:49 UTC, olimed commented on sources/views/form/index.js
> +		this.uploader.files.data.each(async (obj) => {
зачем здесь `async`?

2021-11-27 10:08 UTC, kkazlov commented on sources/views/form/index.js
> +		this.uploader.files.data.each(async (obj) => {
done

2021-11-27 10:17 UTC, kkazlov commented on sources/views/form/files-table.js
> +				.then((files) => {
done

2021-11-29 09:33 UTC, olimed approved these changes

2021-11-29 09:41 UTC, kkazlov commented on sources/views/form/index.js
> +		this.dp.on();
Исправил

2021-11-29 09:42 UTC, kkazlov commented on sources/views/form/index.js
> +		this.dp = webix.dp(albumsDB);
Исправил

2021-12-02 16:41 UTC, ekosiy approved these changes

2021-12-02 16:43 UTC, merged